### ISSUE TITLE
Markdoc server crashed.

### ISSUE THREAD

**Issue by louiss0** [markdoc-extra/vscode-markdoc#10]
The server crashed 5 times today I don't know what is going on but It seems like it Does not like how Astro is being used.

```
Markdoc config (Astro) detected at c:\Users\louis\Desktop\web-projects\ui\markdoc-test

c:\Users\louis\.vscode\extensions\mohitsingh.markdoc-0.6.0\node_modules\esbuild-wasm\lib\main.js:1063
        return callback(new Error(error), null);
                        ^

Error: The service was stopped: spawn node ENOENT
    at c:\Users\louis\.vscode\extensions\mohitsingh.markdoc-0.6.0\node_modules\esbuild-wasm\lib\main.js:1063:25
    at responseCallbacks.<computed> (c:\Users\louis\.vscode\extensions\mohitsingh.markdoc-0.6.0\node_modules\esbuild-wasm\lib\main.js:687:9)
    at ChildProcess.afterClose (c:\Users\louis\.vscode\extensions\mohitsingh.markdoc-0.6.0\node_modules\esbuild-wasm\lib\main.js:677:28)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

```

You can use this repo to find out what is going on [Markdoc Test Repo](https://stackblitz.com/edit/withastro-astro-zdtvav?file=README.md)

**Comment by mohitsinghs** [comment]
@louiss0 I tried your [repo](https://github.com/louiss0/markdoc-test) on my machine and it is working as expected. Looks like something OS specific. Let me dig further into it.

**Comment by louiss0** [comment]
> @louiss0 I tried your [repo](https://github.com/louiss0/markdoc-test) on my machine ( Ubuntu 22.04 ) and it is working as expected. Looks like something OS specific. Let me dig further into it.

I'm using Windows.

**Comment by mohitsinghs** [comment]
With v0.6.1, The extension should work with basic functionality without crashing even if config parsing fails. Still, let's keep this issue open till we get to the reason of crash.

**Comment by louiss0** [comment]
> With v0.6.1, The extension should work with basic functionality without crashing even if config parsing fails. Still, let's keep this issue open till we get to the reason of crash.

Ok tell me about any new updates.

**Comment by mohitsinghs** [comment]
@louiss0  There is an [official extension](https://marketplace.visualstudio.com/items?itemName=Stripe.markdoc-language-support) now that might solve issues you are facing.
