### ISSUE TITLE
What about vs code preview of markdoc files?

### ISSUE THREAD

**Issue by alexbjorlig** [markdoc-extra/vscode-markdoc#5]
If I add this to my settings: 

```
"files.associations": {
  "*.md": "markdoc"
}
```

The preview button is now gone?

<img width="567" alt="Screenshot 2022-09-06 at 07 42 20" src="https://user-images.githubusercontent.com/9967422/188555732-d356ce14-bece-4388-b424-9b14fc16d74d.png">

How do you write/preview markdoc with this extension - maybe I'm missing something.

**Comment by mohitsinghs** [comment]
So far, only syntax highlighting is supported. This and other features such as LSP and formatting are missing as of now.

For preview, we can't reuse the **markdown** one because **markdoc** is a superset of **markdown** and we wouldn't be able to render tags etc without a custom previewer.

**Comment by mohitsinghs** [comment]
@alexbjorlig Looks like an official extension for Markdoc is out and supports preview among various other features.

- [extension](https://marketplace.visualstudio.com/items?itemName=Stripe.markdoc-language-support)
- [repository](https://github.com/markdoc/language-server)

Closing this as I'll be implementing it anyway when I get time.
